name: Super Linter

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Super-Linter
        uses: super-linter/super-linter@v6.3.0
        with:
          args: --exit-zero --github-token=${{ secrets.GITHUB_TOKEN }}
