
name: Super Linter

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Super-Linter
        uses: super-linter/super-linter@v6.3.0
        with:
          entryPoint: /linting/linters
          args: --exit-zero
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
