---
name: Super Linter
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Super-Linter
        uses: github/super-linter@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/super-linter.yml
